import javax.swing.JPanel;
import java.lang.Runnable;
import java.lang.Thread;
import javax.swing.JComponent;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
public class GamePanel extends JPanel implements Runnable
{
    final int originalTileSize = 16;//16 x 16 tile
    final int scale = 3;
    public final int tileSize = originalTileSize * scale;//48 x 48 tile
    public final int maxScreenCol = 16;
    public final int maxScreenRow = 12;
    public final int screenWidth = tileSize * maxScreenCol;//76 pixel
    public final int screenHeight = tileSize * maxScreenRow;//576 pixel
    //WORLD SETTINGS
    public final int maxWorldCol=50;
    public final int maxWorldRow=50;
    public final int worldWidth=tileSize*maxWorldCol;
    public final int worldHeight=tileSize*maxWorldRow;
    //FPS
    int FPS=60;
    public TileManager tile=new TileManager(this);
    KeyHandler keyH=new KeyHandler();
    //set players default position
    Thread gameThread;//may be used for the fps,'implements' used
    public CollisionChecker cChecker=new CollisionChecker(this);
    public Player player=new Player(this,keyH);
    public GamePanel()
    {
        this.setPreferredSize(new Dimension(screenWidth,screenHeight));
        this.setBackground(Color.black);
        this.setDoubleBuffered(true);
        this.addKeyListener(keyH);
        this.setFocusable(true);//main culprit that other java program ,key input not received
    }
    public void startGameThread()
    {
        gameThread=new Thread(this);
        gameThread.start();//call run()
    }
    //@override
    /*ONE TIMING METHOD
    public void run()
    {
        double drawInterval=Math.pow(10,9)/FPS;//duration to show a single Frame .ie a single frame is shown for 0.016666 seconds 
        double nextDrawTime=System.nanoTime()+drawInterval;//let 4:30 pm
        while(gameThread!=null)
        {
            //1 UPDATE:update information such as character position
            update();
            //2 DRAW: draw the screen with the updated informaton
            repaint();
            
            try{
                double remainingTime=nextDrawTime-System.nanoTime();//now(6:00pm), time spend(6:00-4:30)=1:30 hours
                                     //nextDrawTime>> System.nanoTime(current time) ,hence time taken for update(),repaint() verry less
                                     //as compared to drawinterval time
                remainingTime=remainingTime/1000000;
                if(remainingTime<0)
                {
                    remainingTime=0;
                }
                
                Thread.sleep((long)remainingTime);//this sleep reduces the extr increment of time by the 1/FPS to maintain the timing ie increasing System.nanoTime()
                
                nextDrawTime = nextDrawTime+drawInterval;
            }catch(InterruptedException e)
            {
                e.printStackTrace();
            }
        }
    }*/
    //ANOTHER TIMING METHOD
    public void run()
    {
        double drawInterval=1000000000/FPS;
        double delta=0;
        long lastTime=System.nanoTime();
        long currentTime;
        long timer=0;
        int drawCount=0;
        while(gameThread!=null)
        {
            currentTime=System.nanoTime();
            delta+=(currentTime-lastTime)/drawInterval;//how many 0.01666(FRAMES with 0.0166 interval) can be generated by the subtraction
            timer+=(currentTime-lastTime);
            lastTime=currentTime;
            if(delta>=1)//morethan 1 FRAME can be generated
            {
                update();
                repaint();
                delta--;
                drawCount++;
            }
            if(timer>Math.pow(10,9))
            {
                System.out.println("FPS:"+drawCount);
                timer=0;
                drawCount=0;
            }
        }
    }
    public void update()
    {
        player.update();
    }
    /*public void update()
    {
        if(keyH.upPressed==true)
        {
            playerY=playerY-playerSpeed;
        }
        else if(keyH.downPressed==true)
        {
            playerY=playerY+playerSpeed;
        }
        else if(keyH.leftPressed==true)
        {
            playerX=playerX-playerSpeed;
        }
        else if(keyH.rightPressed==true)
        {
            playerX=playerX+playerSpeed;
        }
    }*/
    public void paintComponent(Graphics g)//built-in method
    {
        super.paintComponent(g);//super->parent class(JPanel)
        Graphics2D g2= (Graphics2D)g;
        //g2.setColor(Color.white);
        //g2.fillRect(playerX,playerY,tileSize,tileSize);
        tile.draw(g2);
        player.draw(g2);
        g2.dispose();
    }
}